# Generated by Django 4.0.4 on 2022-04-13 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresomascotas',
            fields=[
                ('alimentacion', models.CharField(max_length=50, verbose_name='Alimentacion')),
                ('edad', models.BigIntegerField(verbose_name='Edad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaderescate', models.DateTimeField(verbose_name='Fecha de Rescate')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('enfermedadespasadas', models.CharField(max_length=50, verbose_name='Enfermedades')),
                ('foto', models.FileField(upload_to='')),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresomascotas_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoptante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IngresoMascotas.ingresomascotas')),
            ],
        ),
        migrations.AddField(
            model_name='ingresomascotas',
            name='vacunacion',
            field=models.ManyToManyField(blank=True, to='IngresoMascotas.vacuna'),
        ),
    ]
