# Generated by Django 4.0.4 on 2022-04-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IngresoMascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razones', models.TextField()),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IngresoMascotas.ingresomascotas')),
                ('persona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.persona')),
            ],
        ),
    ]
